global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'telegram'

receivers:
  - name: 'telegram'
    webhook_configs:
      - url: 'https://api.telegram.org/bot8003916403:AAGKyTzbDeZLENP55IUje6uNfmacK1FqtdI/sendMessage'
        send_resolved: true
        http_config:
          proxy_url: ''
        title: '🚨 Alert: {{ .GroupLabels.alertname }}'
        text: 'Instance: {{ .GroupLabels.instance }}'
