{
 "title": "PostgreSQL - Обзорный дашборд",
 "tags": [
  "postgresql",
  "overview"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Версия PostgreSQL",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_server_version_num/10000 + pg_settings_server_version_num%10000 /100"
    }
   ]
  },
  {
   "title": "Время работы системы",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - node_boot_time_seconds) / 86400*24"
    }
   ]
  },
  {
   "title": "Доступность PostgreSQL",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 10, "x": 9, "y": 0 },
   "targets": [
    { "expr": "pg_up", "legendFormat": "PostgreSQL" }
   ]
  },
  {
   "title": "Использование памяти",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100",
     "legendFormat": "RAM %"
    }
   ]
  },
  {
   "title": "Использование CPU",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "CPU %"
    }
   ]
  },
  {
   "title": "Занятое на диске место",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"} * 100)"
    }
   ]
  },
  {
   "title": "Нагрузка системы",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 10, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "node_load1", "legendFormat": "1 min" },
    { "expr": "node_load5", "legendFormat": "5 min" },
    { "expr": "node_load15", "legendFormat": "15 min" }
   ]
  },
  {
   "title": "Активные подключения",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{state=\"active\"})",
     "legendFormat": "Активные"
    }
   ]
  },
  {
   "title": "Количество процессов",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 3, "y": 12 },
   "targets": [
    {
     "expr": "node_procs_running + node_procs_blocked\r\n"
    }
   ]
  },
  {
   "title": "Подключения по состоянию",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Disk I/O Load",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 8, "y": 18 },
   "targets": [
    {
     "expr": "rate(node_disk_written_bytes_total{device=\"sda\"}[5m])\r\n-rate(node_disk_read_bytes_total{device=\"sda\"}[5m])"
    }
   ]
  }
 ]
}